import { betterAuth } from "better-auth";
import { prismaAdapter } from "better-auth/adapters/prisma";
import { magicLink, organization } from "better-auth/plugins";

import { prisma } from "./db.server";
import { env } from "./env.server";
import { sendInvitationEmail, sendMagicLinkEmail } from "./email.server";
import { ac, roles } from "./permissions";

/**
 * Better Auth 1.7.5, self-hosted in Growzar's own database (D-28).
 *
 * The organization plugin owns users, sessions, accounts, members and
 * invitations. Those tables are generated by its CLI into `schema.prisma`
 * (`npm run auth:generate`) and are never hand-written — the old hub's
 * Firebase-era user model is deliberately not carried over.
 *
 * Google sign-in and two-factor are later, not now, but nothing here designs
 * them out: both are plugin additions against this same config.
 */
export const auth = betterAuth({
  appName: "Growzar",
  baseURL: env.BETTER_AUTH_URL,
  secret: env.BETTER_AUTH_SECRET,

  database: prismaAdapter(prisma, { provider: "postgresql" }),

  // Table names are left at Better Auth's defaults on purpose. `modelName`
  // renames the Prisma *model* as well as the table, so asking for snake_case
  // tables buys `prisma.organization_roles` in every call site. Growzar's own
  // tables stay snake_case plural; the auth tables stay as generated.

  emailAndPassword: {
    enabled: true,
    // A merchant signing up from an app has already proven ownership of the
    // shop through the claim token (§10), so a second round trip through the
    // inbox buys nothing at sign-up. Magic links cover "I forgot my password".
    requireEmailVerification: false,
    minPasswordLength: 10,
  },

  session: {
    expiresIn: 60 * 60 * 24 * 30,
    updateAge: 60 * 60 * 24,
    cookieCache: { enabled: true, maxAge: 60 * 5 },
  },

  advanced: {
    // Growzar is one host; a cross-site cookie would only widen the surface.
    defaultCookieAttributes: {
      sameSite: "lax",
      secure: env.NODE_ENV === "production",
      httpOnly: true,
    },
  },

  plugins: [
    magicLink({
      expiresIn: 60 * 10,
      // Signing in with a link a person has never signed up with is how the
      // claim flow will attach a store to a brand-new account (G-GZR-3), so
      // sign-up stays enabled here.
      disableSignUp: false,
      sendMagicLink: async ({ email, url }) => {
        const result = await sendMagicLinkEmail(email, url);
        if (!result.sent && result.reason === "send_failed") {
          // Throwing would tell an unauthenticated caller whether the address
          // exists. Log and let the request look identical either way.
          console.error(`[auth] magic link email failed for a recipient`);
        }
      },
    }),

    organization({
      ac,
      roles,
      creatorRole: "owner",
      // Custom roles per organization (D-12). The tables this adds are part of
      // the generated schema, so it is enabled from day 1 even though the UI
      // for it lands in G-GZR-2.
      dynamicAccessControl: { enabled: true, maximumRolesPerOrganization: 20 },
      // Growzar's grouping unit is the store, not a team; store scope lives on
      // the member row instead (G-GZR-2).
      teams: { enabled: false },
      schema: {
        organization: {
          additionalFields: {
            // Growzar's own column (see prisma/schema.prisma). It is declared
            // here so `createOrganization` accepts and stores it; otherwise the
            // plugin would insert a row without it and Postgres would reject
            // the write. There is no default on purpose: money across stores
            // converts into this currency, and a guessed base currency is the
            // kind of silent wrong number rule #4 exists to prevent.
            baseCurrency: { type: "string", required: true, input: true },
          },
        },
      },
      invitationExpiresIn: 60 * 60 * 24 * 7,
      cancelPendingInvitationsOnReInvite: true,
      sendInvitationEmail: async ({ id, email, role, organization, inviter }) => {
        await sendInvitationEmail({
          to: email,
          organizationName: organization.name,
          inviterName: inviter.user.name || inviter.user.email,
          role,
          url: `${env.BETTER_AUTH_URL}/invitations/${id}`,
        });
      },
    }),
  ],
});

export type Auth = typeof auth;
export type Session = typeof auth.$Infer.Session;
