-- Retainify's read feeds as synced entities (Phase 5, G-GZR5-2).
ALTER TYPE "SyncEntity" ADD VALUE IF NOT EXISTS 'MESSAGE';
ALTER TYPE "SyncEntity" ADD VALUE IF NOT EXISTS 'JOURNEY';
ALTER TYPE "SyncEntity" ADD VALUE IF NOT EXISTS 'ENROLLMENT';
ALTER TYPE "SyncEntity" ADD VALUE IF NOT EXISTS 'CHECKOUT';
ALTER TYPE "SyncEntity" ADD VALUE IF NOT EXISTS 'CONSENT';
ALTER TYPE "SyncEntity" ADD VALUE IF NOT EXISTS 'CONSENT_EVENT';
