-- Preventify's read feeds as synced entities (Phase 5, G-GZR5-8).
ALTER TYPE "SyncEntity" ADD VALUE IF NOT EXISTS 'FORM_ORDER';
ALTER TYPE "SyncEntity" ADD VALUE IF NOT EXISTS 'FORM_ABANDONMENT';
ALTER TYPE "SyncEntity" ADD VALUE IF NOT EXISTS 'FORM_SETTINGS';
ALTER TYPE "SyncEntity" ADD VALUE IF NOT EXISTS 'FORM_SETTINGS_CHANGE';
ALTER TYPE "SyncEntity" ADD VALUE IF NOT EXISTS 'OFFER';
ALTER TYPE "SyncEntity" ADD VALUE IF NOT EXISTS 'OFFER_EVENT';
ALTER TYPE "SyncEntity" ADD VALUE IF NOT EXISTS 'FRAUD_EVENT';
