-- Inventorify's read feeds as synced entities (Phase 5, G-GZR5-1).
ALTER TYPE "SyncEntity" ADD VALUE IF NOT EXISTS 'INVENTORY_VARIANT';
ALTER TYPE "SyncEntity" ADD VALUE IF NOT EXISTS 'STOCK_LEVEL';
ALTER TYPE "SyncEntity" ADD VALUE IF NOT EXISTS 'DAILY_SALES';
ALTER TYPE "SyncEntity" ADD VALUE IF NOT EXISTS 'STOCK_SNAPSHOT';
ALTER TYPE "SyncEntity" ADD VALUE IF NOT EXISTS 'PURCHASE_ORDER';
ALTER TYPE "SyncEntity" ADD VALUE IF NOT EXISTS 'SUPPLIER';
ALTER TYPE "SyncEntity" ADD VALUE IF NOT EXISTS 'RETURN_RESTOCK';
